#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

cartridge_type="python-2.7"
source $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin/activate

echo "Install & Update Django Xadmin form source"
pip install --upgrade git+git://github.com/sshwsfc/django-xadmin.git

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py collectstatic --noinput
