#!/usr/bin/env python

import os
import sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'demo.settings'
sys.path.append(os.environ['OPENSHIFT_REPO_DIR'])

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
